### ISSUE TITLE
FR: Support using firmware sourcr in same repo

### ISSUE THREAD

**Issue by mk-pmb** [mk-pmb/nodemcu-firmware-build-as-github-action#1]
```yaml
with:
    firmware_repo: '.'
    firmware_repo: './nodemcu-firmware'
```

also magic branch name `=` should mean same-named.
